volumes:
  db_volume:

services:
  webserver:
    image: nginx:1.23.2-alpine
    hostname: webserver
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
    ports:
      - 80:80
#      - 443:443

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    hostname: php

  # https://hub.docker.com/_/mariadb
  database:
    image: mariadb:10.6.5
    hostname: database-server
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    ports:
      - 3306:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=${DATABASE_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 1s
      retries: 15
    volumes:
      - db_volume:/var/lib/mysql